### ISSUE TITLE
How to access the dash routes

### ISSUE THREAD

**Issue by Demborg** [toddbirchard/plotlydash-flask-tutorial#3]
Hey and thanks for your awesome tutorial.
I am trying to use this to add a layer of authenticaion over my dash app, which I hoped I could do by adding a decorator to the route for the dash. but even when hacking dash like this I don't understand how I could do that?

**Comment by rgime** [comment]
> Hey and thanks for your awesome tutorial.
> I am trying to use this to add a layer of authenticaion over my dash app, which I hoped I could do by adding a decorator to the route for the dash. but even when hacking dash like this I don't understand how I could do that?

@Demborg, how you manage to do this ? Any tips ? Thanks.
